### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by leepeterson** [wp-api-libraries/wp-serverpilot-api#1]
Any progress being made on this idea? Would love to find out more and contribute if I can.

**Comment by bhubbard** [comment]
@leepeterson We have created the repo for many third party apis, and have started some, this one for serverpilot hasn't been started on, but we do accept pull requests ;)

**Comment by leepeterson** [comment]
Do let me know if/how I can help!

**Comment by bhubbard** [comment]
@leepeterson Feel free to fork the repo and start the project.
